apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-service
  template:
    metadata:
      labels:
        app: hello-service
    spec:
      containers:
      - name: hello-service
        image: siriuppula/hello-service
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: NodePort
  selector:
    app: hello-service
  ports:
    - port: 3000        # Port on which the service is exposed inside the cluster
      targetPort: 3000   # Port on the container to which the service routes traffic
      nodePort: 30002    # Port on each node where the service is expose
