apiVersion: apps/v1
kind: Deployment
metadata:
  name: world-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: world-service
  template:
    metadata:
      labels:
        app: world-service
    spec:
      containers:
      - name: world-service
        image: siriuppula/world-service
        ports:
        - containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: world-service
spec:
  type: NodePort
  selector:
    app: world-service
  ports:
    - port: 3001         # Port on which the service is exposed inside the cluster
      targetPort: 3001   # Port on the container to which the service routes traffic
      nodePort: 30003    # Port on each node where the service is exposed
